#!/bin/bash

echo "=========================================="
echo "Testing Sealos SRE Agent HTTP API (hzh zone only)"
echo "=========================================="
echo ""

BASE_URL="http://localhost:3000"
ZONE="hzh"
NAMESPACE="ns-mh69tey1"

echo "1. Testing API documentation endpoint..."
curl -s "$BASE_URL/api"
echo -e "\n"

echo "2. Testing health check (hzh zone)..."
curl -s "$BASE_URL/health?zone=$ZONE"
echo -e "\n"

echo "3. Testing list pods API (requires namespace parameter)..."
curl -s "$BASE_URL/api/pods?zone=$ZONE"
echo -e "\n"

echo "4. Testing list pods API with parameters..."
curl -s "$BASE_URL/api/pods?zone=$ZONE&namespace=$NAMESPACE"
echo -e "\n"

echo "5. Testing list nodes API..."
curl -s "$BASE_URL/api/nodes?zone=$ZONE"
echo -e "\n"

echo "6. Testing list devbox API..."
curl -s "$BASE_URL/api/devbox?zone=$ZONE&namespace=$NAMESPACE"
echo -e "\n"

echo "7. Testing none API (always returns empty)..."
curl -s "$BASE_URL/api/none?zone=$ZONE&namespace=$NAMESPACE"
echo -e "\n"

echo "=========================================="
echo "HTTP API Test Complete!"
echo "=========================================="
echo ""
echo "Available endpoints:"
echo "  GET  /api                                - API documentation"
echo "  GET  /health?zone=<zone>                 - Health check"
echo "  GET  /api/pods?zone=<zone>&namespace=<ns>"
echo "  GET  /api/devbox?zone=<zone>&namespace=<ns>"
echo "  GET  /api/cluster?zone=<zone>&namespace=<ns>"
echo "  GET  /api/quota?zone=<zone>&namespace=<ns>"
echo "  GET  /api/ingress?zone=<zone>&namespace=<ns>"
echo "  GET  /api/nodes?zone=<zone>"
echo "  GET  /api/none?zone=<zone>&namespace=<ns> - Always returns \"空\""
echo "  GET  /api/cronjobs?zone=<zone>&namespace=<ns>"
echo "  GET  /api/events?zone=<zone>&namespace=<ns>"
echo "  GET  /api/account?zone=<zone>&namespace=<ns>"
echo "  GET  /api/debt?zone=<zone>&namespace=<ns>"
echo "  GET  /api/objectstoragebucket?zone=<zone>&namespace=<ns>"
echo "  GET  /api/certificate?zone=<zone>&namespace=<ns>"
echo "  POST /api/inspect                        - Inspect resource"
echo ""
echo "Usage examples:"
echo "  curl 'http://localhost:3000/api/pods?zone=$ZONE&namespace=$NAMESPACE'"
echo "  curl 'http://localhost:3000/api/devbox?zone=$ZONE&namespace=$NAMESPACE'"
echo "  curl 'http://localhost:3000/api/none?zone=$ZONE&namespace=$NAMESPACE'"
echo "  curl -X POST http://localhost:3000/api/inspect -H 'Content-Type: application/json' -d '{\"zone\":\"$ZONE\",\"resource\":\"pod\",\"name\":\"my-sealos-agent\",\"namespace\":\"$NAMESPACE\"}'"
echo ""
